### ISSUE TITLE
OPENAIのAPI KEYはダミーでしょうか？

### ISSUE THREAD

**Issue by QtDogBow** [ronron-gh/AI_StackChan2_FuncCall#3]
WebVoiceVoxTTS.cppにsk-**のキーがコメントアウトされています。
ダミーとは思いますが、念のため連絡しておきます。

**Comment by ronron-gh** [comment]
ご連絡ありがとうございます。ご指摘のファイルはrobo8080さんのAI StachChan2から引き継いでいます。不要なコードのようなので削除します。robo8080さんには私から連絡いたします。

**Comment by QtDogBow** [comment]
それでは連絡をお願いします。
後で気が付きましたが、同じファイルに"key="で検索するともう一か所怪しいところがあります。この件もついでにお願いします。

**Comment by ronron-gh** [comment]
了解です。もう一か所の方も連絡します。

**Comment by ronron-gh** [comment]
robo8080さんに確認したところ、無効なキーとのことでしたので、本件クローズします。
